"use client";

import { useState, useTransition } from "react";
import { BarChart3, CheckCircle2, FileText } from "lucide-react";
import type { SeoReport } from "@/lib/types";
import { generateSeoReportAction, updateSeoReportAction } from "@/lib/actions";
import { cn } from "@/lib/utils";

function currentPeriod(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

export function SeoReportingPanel({ projectId, reports }: { projectId: string; reports: SeoReport[] }) {
  const [isPending, startTransition] = useTransition();
  const period = currentPeriod();
  const hasCurrent = reports.some((r) => r.period === period);

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <BarChart3 size={16} className="text-accent-400" />
          <h2 className="text-sm font-semibold uppercase tracking-wide text-neutral-400">Reporting</h2>
        </div>
        {!hasCurrent && (
          <button
            type="button"
            disabled={isPending}
            onClick={() => startTransition(() => generateSeoReportAction(projectId, period))}
            className="flex items-center gap-1.5 rounded-lg bg-accent-500 px-3 py-1.5 text-xs font-medium text-base-950 hover:bg-accent-400 disabled:opacity-60"
          >
            <FileText size={13} />
            {isPending ? "Generating…" : `Generate ${period}`}
          </button>
        )}
      </div>

      {reports.length === 0 && (
        <p className="rounded-lg border border-dashed border-base-700 p-6 text-center text-sm text-neutral-500">
          No reports yet. Generate this month&apos;s to pull in keyword movement, completed tasks, and backlinks created.
        </p>
      )}

      <div className="flex flex-col gap-3">
        {reports.map((report) => (
          <ReportCard key={report.id} projectId={projectId} report={report} />
        ))}
      </div>
    </div>
  );
}

function ReportCard({ projectId, report }: { projectId: string; report: SeoReport }) {
  const [isPending, startTransition] = useTransition();
  const [summary, setSummary] = useState(report.summary);

  return (
    <div className="rounded-xl2 border border-base-700/60 bg-base-850 p-4">
      <div className="mb-2 flex items-center justify-between">
        <h3 className="text-sm font-semibold text-neutral-100">{report.period}</h3>
        <button
          type="button"
          disabled={isPending || report.sentToClient}
          onClick={() => startTransition(() => updateSeoReportAction(report.id, projectId, { sentToClient: true }))}
          className={cn(
            "flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-medium",
            report.sentToClient ? "bg-accent-500/15 text-accent-400" : "border border-base-600 text-neutral-400 hover:text-accent-300",
          )}
        >
          <CheckCircle2 size={12} />
          {report.sentToClient ? "Sent to client" : "Mark sent"}
        </button>
      </div>
      <textarea
        value={summary}
        onChange={(e) => setSummary(e.target.value)}
        onBlur={() => summary !== report.summary && startTransition(() => updateSeoReportAction(report.id, projectId, { summary }))}
        rows={6}
        className="w-full rounded-md border border-base-600 bg-base-900 px-3 py-2 text-sm text-neutral-100 focus:border-accent-500 focus:outline-none"
      />
      {report.generatedByName && (
        <p className="mt-1.5 text-[11px] text-neutral-600">Generated by {report.generatedByName}</p>
      )}
    </div>
  );
}
