-- Chrome employee activity, device pairing, AI prompt audit, project matching and WebRTC signaling.
create table if not exists public.freelance_hq_extension_pairing_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.freelance_hq_profiles(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.freelance_hq_employee_devices (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.freelance_hq_profiles(id) on delete cascade,
  device_id text not null,
  extension_install_id text not null unique,
  token_hash text not null unique,
  device_label text not null default '',
  user_agent text not null default '',
  paired_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_status text not null default 'active' check (last_status in ('active','idle','offline')),
  current_domain text not null default '',
  current_url text not null default '',
  current_title text not null default '',
  current_project_id uuid references public.freelance_hq_projects(id) on delete set null,
  revoked_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(employee_id, device_id, extension_install_id)
);

create table if not exists public.freelance_hq_browser_sessions (
  id uuid primary key,
  employee_id uuid not null references public.freelance_hq_profiles(id) on delete cascade,
  device_id uuid not null references public.freelance_hq_employee_devices(id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz,
  last_seen_at timestamptz not null,
  status text not null default 'active' check (status in ('active','idle','offline','ended')),
  created_at timestamptz not null default now()
);

create table if not exists public.freelance_hq_activity_logs (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.freelance_hq_profiles(id) on delete cascade,
  device_id uuid not null references public.freelance_hq_employee_devices(id) on delete cascade,
  session_id uuid references public.freelance_hq_browser_sessions(id) on delete set null,
  project_id uuid references public.freelance_hq_projects(id) on delete set null,
  activity_type text not null check (activity_type in ('active','idle','tab_switch','session_start','session_end','heartbeat','offline')),
  domain text not null default '',
  url text not null default '',
  page_title text not null default '',
  started_at timestamptz not null,
  ended_at timestamptz,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.freelance_hq_ai_prompt_logs (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.freelance_hq_profiles(id) on delete cascade,
  device_id uuid not null references public.freelance_hq_employee_devices(id) on delete cascade,
  session_id uuid references public.freelance_hq_browser_sessions(id) on delete set null,
  project_id uuid references public.freelance_hq_projects(id) on delete set null,
  platform text not null check (platform in ('chatgpt','claude')),
  prompt_text text not null,
  submitted_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.freelance_hq_project_domain_mappings (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.freelance_hq_projects(id) on delete cascade,
  match_type text not null default 'domain' check (match_type in ('domain','url_prefix','github_repo')),
  pattern text not null,
  label text not null default '',
  is_active boolean not null default true,
  created_by uuid references public.freelance_hq_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, match_type, pattern)
);

create table if not exists public.freelance_hq_screen_share_sessions (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.freelance_hq_profiles(id) on delete cascade,
  device_id uuid not null references public.freelance_hq_employee_devices(id) on delete cascade,
  status text not null default 'waiting' check (status in ('waiting','active','ended')),
  microphone_enabled boolean not null default false,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  last_seen_at timestamptz not null default now()
);

create table if not exists public.freelance_hq_screen_share_signals (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.freelance_hq_screen_share_sessions(id) on delete cascade,
  sender text not null check (sender in ('employee','admin')),
  signal_type text not null check (signal_type in ('offer','answer','ice')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.freelance_hq_activity_settings (
  id boolean primary key default true check (id = true),
  retention_days integer not null default 60 check (retention_days between 1 and 3650),
  updated_by uuid references public.freelance_hq_profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.freelance_hq_activity_settings(id, retention_days)
values (true, 60)
on conflict (id) do nothing;

create index if not exists fhq_pairing_user_created_idx on public.freelance_hq_extension_pairing_tokens(user_id, created_at desc);
create index if not exists fhq_devices_employee_seen_idx on public.freelance_hq_employee_devices(employee_id, last_seen_at desc);
create index if not exists fhq_activity_employee_started_idx on public.freelance_hq_activity_logs(employee_id, started_at desc);
create index if not exists fhq_activity_project_started_idx on public.freelance_hq_activity_logs(project_id, started_at desc);
create index if not exists fhq_activity_domain_started_idx on public.freelance_hq_activity_logs(domain, started_at desc);
create index if not exists fhq_activity_device_started_idx on public.freelance_hq_activity_logs(device_id, started_at desc);
create index if not exists fhq_prompts_employee_submitted_idx on public.freelance_hq_ai_prompt_logs(employee_id, submitted_at desc);
create index if not exists fhq_prompts_device_submitted_idx on public.freelance_hq_ai_prompt_logs(device_id, submitted_at desc);
create index if not exists fhq_browser_sessions_employee_started_idx on public.freelance_hq_browser_sessions(employee_id, started_at desc);
create index if not exists fhq_mapping_pattern_idx on public.freelance_hq_project_domain_mappings(pattern);
create index if not exists fhq_screen_share_employee_started_idx on public.freelance_hq_screen_share_sessions(employee_id, started_at desc);
create index if not exists fhq_screen_signal_session_id_idx on public.freelance_hq_screen_share_signals(session_id, id);

alter table public.freelance_hq_extension_pairing_tokens enable row level security;
alter table public.freelance_hq_employee_devices enable row level security;
alter table public.freelance_hq_browser_sessions enable row level security;
alter table public.freelance_hq_activity_logs enable row level security;
alter table public.freelance_hq_ai_prompt_logs enable row level security;
alter table public.freelance_hq_project_domain_mappings enable row level security;
alter table public.freelance_hq_screen_share_sessions enable row level security;
alter table public.freelance_hq_screen_share_signals enable row level security;
alter table public.freelance_hq_activity_settings enable row level security;

revoke all on table
  public.freelance_hq_extension_pairing_tokens,
  public.freelance_hq_employee_devices,
  public.freelance_hq_browser_sessions,
  public.freelance_hq_activity_logs,
  public.freelance_hq_ai_prompt_logs,
  public.freelance_hq_project_domain_mappings,
  public.freelance_hq_screen_share_sessions,
  public.freelance_hq_screen_share_signals,
  public.freelance_hq_activity_settings
from anon, authenticated;

grant select, insert, update, delete on table
  public.freelance_hq_extension_pairing_tokens,
  public.freelance_hq_employee_devices,
  public.freelance_hq_browser_sessions,
  public.freelance_hq_activity_logs,
  public.freelance_hq_ai_prompt_logs,
  public.freelance_hq_project_domain_mappings,
  public.freelance_hq_screen_share_sessions,
  public.freelance_hq_screen_share_signals,
  public.freelance_hq_activity_settings
to service_role;

grant usage, select on sequence public.freelance_hq_screen_share_signals_id_seq to service_role;
