-- Harden Chrome extension device authentication and pairing abuse controls.
alter table public.freelance_hq_employee_devices
  add column if not exists token_expires_at timestamptz,
  add column if not exists token_rotated_at timestamptz,
  add column if not exists last_health_at timestamptz;

update public.freelance_hq_employee_devices
set token_expires_at = coalesce(token_expires_at, now() + interval '45 days'),
    token_rotated_at = coalesce(token_rotated_at, paired_at),
    last_health_at = coalesce(last_health_at, last_seen_at);

alter table public.freelance_hq_employee_devices
  alter column token_expires_at set not null,
  alter column token_rotated_at set not null;

create table if not exists public.freelance_hq_extension_pair_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists fhq_pair_attempt_ip_created_idx
  on public.freelance_hq_extension_pair_attempts(ip_hash, created_at desc);

alter table public.freelance_hq_extension_pair_attempts enable row level security;
revoke all on table public.freelance_hq_extension_pair_attempts from anon, authenticated;
grant select, insert, delete on table public.freelance_hq_extension_pair_attempts to service_role;
grant usage, select on sequence public.freelance_hq_extension_pair_attempts_id_seq to service_role;
